"use client";

// Phase 8 single-variation panel (spec section 25-27): the only place a generated character is
// composed in Three.js, plus per-field locks and the single-character reroll.
import { useMemo } from "react";
import { PALETTE_SLOTS } from "@/domain/constants";
import { SLOT_LABEL } from "@/domain/builder-recipe";
import { EXPORT_ASSET_SLOTS } from "@/domain/character-export";
import { LOCK_FIELDS, LOCK_FIELD_LABEL, type GeneratedVariation, type LockField } from "@/domain/variation-generator";
import type { CandidateAsset } from "@/domain/variation-candidates";
import type { AssetLibrary } from "@/features/asset-library/library";
import { activeAnimationSetFor } from "@/features/library/export-helpers";
import { CharacterPreview } from "@/features/character-builder/character-preview";

export function VariationDetail({ variation, assetsById, library, locks, onToggleLock, onReroll, onOpenInBuilder, busy, message }: {
  variation: GeneratedVariation;
  assetsById: Map<string, CandidateAsset>;
  library: AssetLibrary;
  locks: readonly LockField[];
  onToggleLock: (field: LockField) => void;
  onReroll: () => void;
  onOpenInBuilder: () => void;
  busy: boolean;
  message: string | null;
}) {
  const recipe = variation.recipe;
  const animSet = useMemo(() => activeAnimationSetFor(recipe, library), [recipe, library]);
  const lockSet = new Set(locks);

  return (
    <div className="lib-detail">
      <div className="lib-detail-head">
        <div>
          <h2>{variation.name}</h2>
          <p className="muted">{variation.id} · {recipe.body.base} / {recipe.body.preset} · salt {variation.salt}</p>
          {variation.duplicate && <p className="err">Duplicate Variation（他の Character と完全一致）</p>}
        </div>
      </div>

      <div className="lib-detail-preview">
        <CharacterPreview
          key={`${variation.id}:${variation.salt}:${variation.signature}`}
          recipe={recipe}
          library={library}
          animationSet={animSet}
          animationRole="idle"
          playing
          speed={1}
          loop
          captureSignal={-1}
        />
      </div>

      <div className="lib-detail-body">
        <dl>
          <dt>Body Scale</dt>
          <dd>H {recipe.body.scale.height} / W {recipe.body.scale.bodyWidth} / Head {recipe.body.scale.headScale}</dd>
          {EXPORT_ASSET_SLOTS.map((slot) => {
            const id = recipe.assets[slot] ?? null;
            return (
              <div key={slot} style={{ display: "contents" }}>
                <dt>{SLOT_LABEL[slot]}</dt>
                <dd>{id ? (assetsById.get(id)?.name ?? id) : "—"}{id && <small className="muted"> {id}</small>}</dd>
              </div>
            );
          })}
          <dt>Palette</dt>
          <dd className="pal-row">{PALETTE_SLOTS.map((s) => <span key={s} style={{ background: recipe.palette[s] }} title={`${s} ${recipe.palette[s]}`} />)}</dd>
          <dt>Animation Set</dt><dd>{animSet}</dd>
          <dt>Generated By</dt>
          <dd>{recipe.generation ? `${recipe.generation.preset} · seed ${recipe.generation.seed} · #${recipe.generation.index}` : "—"}</dd>
        </dl>

        <div className="lib-detail-section">
          <h3>Lock（Reroll 時に固定する項目）</h3>
          <ul className="var-locks">
            {LOCK_FIELDS.map((field) => (
              <li key={field}>
                <label className="check">
                  <input type="checkbox" checked={lockSet.has(field)} onChange={() => onToggleLock(field)} />
                  {lockSet.has(field) ? "🔒 " : ""}{LOCK_FIELD_LABEL[field]}
                </label>
              </li>
            ))}
          </ul>
        </div>

        {variation.warnings.length > 0 && (
          <div className="lib-detail-section">
            <h3>Warnings</h3>
            <ul className="hist-list">{variation.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul>
          </div>
        )}

        <div className="lib-actions">
          <button type="button" disabled={busy} onClick={onReroll}>Reroll</button>
          <button type="button" disabled={busy} onClick={onOpenInBuilder}>Open in Character Builder</button>
        </div>
        {message && <p className="save-msg">{message}</p>}
        <p className="muted">Reroll は この Character だけを引き直します。他の Character には影響しません。</p>
      </div>
    </div>
  );
}
